Unit test full + incardon + gonciarz on jenkins + generic script

diff --git a/build_and_test b/build_and_test
--- a/build_and_test
+++ b/build_and_test
@@ -3,16 +3,34 @@
 echo "Set environment"
 
 # For unkown reason source the file on the slave does not work so we have to do in this horrible way
-export JAVA_HOME=/usr/lib/jvm/java-6-oracle
-export FIJI_MOSAIC_PLUGIN_PATH=/home/jenkins/Fiji.app/plugins/Mosaic_ToolSuite
-export MOSAIC_PLUGIN_TEST_DATA_PATH=/home/jenkins/workspace/Mosaic_ToolSuite/label/nyu/plugin/Jtest_data/
+~/.bashrc
 
-
-export JAVA_HOME=/usr/lib/jvm/java-6-oracle
 cd plugin
 
 ant main
+if [ $? -ne 0 ]
+then
+        echo "Error compiling"
+        exit 1
+fi
 
-cd ~/Fiji.app
+ant jtest
+
+if [ $? -ne 0 ]
+then
+	echo "Error in the tests"
+	exit 1
+fi
+
+cd $FIJI_MOSAIC_PLUGIN_PATH/../..
 
 ./ImageJ-linux64 -batch test.ijm "username=incardon"
+
+# check if tmp/test has succeful file
+
+if [ ! -e "/tmp/test/succeful"  ]
+then
+	echo "Error in the tests"
+	exit 1
+fi
+
